window.KEY_COVERAGE_CODES = [
  "Backquote",
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "Digit0",
  "Minus",
  "Equal",
  "Backspace",
  "Tab",
  "KeyQ",
  "KeyW",
  "KeyE",
  "KeyR",
  "KeyT",
  "KeyY",
  "KeyU",
  "KeyI",
  "KeyO",
  "KeyP",
  "BracketLeft",
  "BracketRight",
  "Backslash",
  "CapsLock",
  "KeyA",
  "KeyS",
  "KeyD",
  "KeyF",
  "KeyG",
  "KeyH",
  "KeyJ",
  "KeyK",
  "KeyL",
  "Semicolon",
  "Quote",
  "Enter",
  "ShiftLeft",
  "KeyZ",
  "KeyX",
  "KeyC",
  "KeyV",
  "KeyB",
  "KeyN",
  "KeyM",
  "Comma",
  "Period",
  "Slash",
  "ShiftRight",
  "ControlLeft",
  "AltLeft",
  "MetaLeft",
  "Space",
  "MetaRight",
  "AltRight",
  "ContextMenu",
  "ControlRight",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
];

window.KEY_COMBO_DEFINITIONS_RAW = [
  { id: "cmd_shift_4", keys: ["Meta", "Shift", "Digit4"], labelIndex: 0 },
  { id: "cmd_shift_3", keys: ["Meta", "Shift", "Digit3"], labelIndex: 1 },
  { id: "cmd_c", keys: ["Meta", "KeyC"], labelIndex: 2 },
  { id: "cmd_v", keys: ["Meta", "KeyV"], labelIndex: 3 },
  { id: "ctrl_alt_cmd_8", keys: ["Control", "Alt", "Meta", "Digit8"], labelIndex: 4 },
];

window.KEY_TEST_SEQUENCE = ["cmd_c", "cmd_v", "cmd_shift_3"];
